#!/bin/bash


# sed -e "s/..\/legacy\/react-to-webcomponent/react-to-webcomponent\/render/g" -e "s/.*react-dom.*/import ReactDOM from 'react-dom'/g" src/tests/react-to-webcomponent.test.jsx > src/tests/environments/react16/react-to-webcomponent.test.jsx

cd src/tests/environments/react16
node copyTest.js
npm i
npm install --install-links ../../../..
cd ../../../../

# sed -e "s/..\/legacy\/react-to-webcomponent/react-to-webcomponent\/render/g" -e "s/.*react-dom.*/import ReactDOM from 'react-dom'/g" src/tests/react-to-webcomponent.test.jsx > src/tests/environments/react17/react-to-webcomponent.test.jsx

cd src/tests/environments/react17
node copyTest.js
npm i
npm install --install-links ../../../..
cd ../../../../


# sed "s/..\/legacy\/react-to-webcomponent/react-to-webcomponent/g" src/tests/react-to-webcomponent.test.jsx > src/tests/environments/react18/react-to-webcomponent.test.jsx

cd src/tests/environments/react18
node copyTest.js
npm i
npm install --install-links ../../../..
cd ../../../../


# sed -e 's/.\/react-to-webcomponent/react-to-webcomponent/g' -e 's/.*react-dom.*/import React from "preact\/compat"/g' -e '/import React from "react"/d' -e 's/ReactDOM/React/g' src/tests/react-to-webcomponent.test.jsx > src/tests/environments/preact10/react-to-webcomponent.test.jsx

# cd src/tests/environments/preact10
# npm i
# npm install --install-links ../../../..
# cd ../../../../