#!/bin/bash

sed "s/.*react-dom.*/import ReactDOM from 'react-dom'/g" react-to-webcomponent.test.jsx > react16/react-to-webcomponent.test.jsx

cd react16
npm i
cd ..


sed "s/.*react-dom.*/import ReactDOM from 'react-dom'/g" react-to-webcomponent.test.jsx > react17/react-to-webcomponent.test.jsx

cd react17
npm i
cd ..


cp react-to-webcomponent.test.jsx react18

cd react18
npm i
cd .. 
