#!/bin/bash

sed "s/.*react-dom.*/import ReactDOM from 'react-dom'/g" react-to-webcomponent-test.js > react16/react-to-webcomponent-test.js 
cp test.html react16

cd react16
npm i
cd ..


sed "s/.*react-dom.*/import ReactDOM from 'react-dom'/g" react-to-webcomponent-test.js > react17/react-to-webcomponent-test.js
cp test.html react17

cd react17
npm i
cd ..


cp react-to-webcomponent-test.js react18
cp test.html react18

cd react18
npm i
cd ..