#!/bin/bash

cd environments/react16
node copyTest.js
npm ci
cd ../../

cd environments/react17
node copyTest.js
npm ci
cd ../../

cd environments/react18
node copyTest.js
npm ci
cd ../../

# cd src/tests/environments/preact10
# npm i
# npm install --install-links ../../../..
# cd ../../../../


# builds
# cd src/tests/builds/vite
# npm i
# npm install --install-links ../../../..
# npm run build
# node swcBuild.js
# cd ../../../../

# cd src/tests/builds/webpack
# npm i
# npm install --install-links ../../../..
# npm run build
# cd ../../../../
