#!/bin/bash

cd environments/react16
node copyTest.js
npm ci
cd ../../

cd environments/react17
node copyTest.js
npm ci
cd ../../

cd environments/react18
node copyTest.js
npm ci
cd ../../

# cd src/tests/environments/preact10
# npm i
# npm install --install-links ../../../..
# cd ../../../../


# builds
cd builds/vite
npm ci
npm run build
node swcBuild.js
cd ../../

cd builds/webpack
npm ci
npm run build
