name: monorepo-job-publish

inputs:
  directory:
    description: "The directory name."
    required: true
  npm-token:
    description: "The token for publishing the package to npm."
    required: true
  github-token:
    description: "The token for pushing tags and version changes to github.."
    required: true
  segment:
    description: "The version segment to increment: major, minor, patch, or prerelease."
    required: true
  preId:
    description: 'Appended to the prerelease segment. (default: "")'

runs:
  using: "composite"

  steps:
    - name: Setup
      uses: ./.github/actions/setup

    - name: Build
      uses: ./.github/actions/build
      with:
        package: ${{ github.workflow }}

    - name: Publish to NPM
      uses: ./.github/actions/publish-npm
      with:
        package: ${{ github.workflow }}
        directory: ${{ inputs.directory }}
        npm-token: ${{ inputs.npm-token }}
        github-token: ${{ inputs.github-token }}
        segment: ${{ inputs.segment }}
        preId: ${{ inputs.preId }}
